use crate::repos::test_file::ExpectedLineExt;
use crate::repos::test_repo::TestRepo;
use git_ai::authorship::authorship_log_serialization::generate_session_id;
use git_ai::metrics::db::MetricsDatabase;
use git_ai::metrics::{EventAttributes, MetricEvent, PosEncoded, SessionEventValues};
use serde_json::json;
use std::fs;
use std::path::Path;
use std::time::UNIX_EPOCH;

fn isolated_metrics_db_path() -> (tempfile::TempDir, String) {
    let dir = tempfile::tempdir().expect("failed to create isolated metrics db dir");
    let path = dir.path().join("metrics.db");
    (dir, path.to_string_lossy().to_string())
}

fn file_mtime_secs(path: &Path) -> u32 {
    fs::metadata(path)
        .expect("file metadata should be readable")
        .modified()
        .expect("file mtime should be readable")
        .duration_since(UNIX_EPOCH)
        .expect("file mtime should be after epoch")
        .as_secs()
        .min(u32::MAX as u64) as u32
}

fn insert_session_event(
    db_path: &str,
    event_ts: u32,
    external_session_id: &str,
    external_tool_use_id: &str,
    repo_url: Option<&str>,
) -> String {
    let tool = "codex";
    let session_id = generate_session_id(external_session_id, tool);
    let values = SessionEventValues::with_ids(
        json!({
            "type": "assistant",
            "session_id": external_session_id,
        }),
        Some(format!("event-{external_tool_use_id}")),
        None,
        Some(external_tool_use_id.to_string()),
    );
    let mut attrs = EventAttributes::with_version("test")
        .tool(tool)
        .model("gpt-5")
        .external_session_id(external_session_id)
        .session_id(&session_id)
        .trace_id(format!("trace-{external_tool_use_id}"));
    if let Some(repo_url) = repo_url {
        attrs = attrs.repo_url(repo_url);
    }
    let event = MetricEvent::from_values_with_timestamp(values, attrs.to_sparse(), Some(event_ts));
    let event_json = serde_json::to_string(&event).expect("metric event should serialize");

    let mut db = MetricsDatabase::open_at_path(Path::new(db_path))
        .expect("metrics db should open at isolated path");
    db.insert_events(&[event_json])
        .expect("session event should insert");

    session_id
}

#[test]
fn test_session_event_recovery_attributes_uncheckpointed_repo_linked_commit() {
    let (_metrics_db_dir, metrics_db_path) = isolated_metrics_db_path();
    let repo =
        TestRepo::new_with_daemon_env(&[("GIT_AI_TEST_METRICS_DB_PATH", metrics_db_path.as_str())]);
    repo.git(&[
        "remote",
        "add",
        "origin",
        "https://github.com/acme/session-event-recovery.git",
    ])
    .expect("remote add should succeed");
    repo.git(&["commit", "--allow-empty", "-m", "initial"])
        .expect("initial empty commit should succeed");

    let file_path = repo.path().join("generated.txt");
    fs::write(&file_path, "generated by AI before hooks\n").unwrap();
    let recovered_session_id = insert_session_event(
        &metrics_db_path,
        file_mtime_secs(&file_path),
        "external-repo-linked-session",
        "tool-use-repo-linked",
        Some("https://github.com/acme/session-event-recovery"),
    );

    let commit = repo
        .stage_all_and_commit("Recover uncheckpointed AI")
        .expect("commit should succeed");

    let mut file = repo.filename("generated.txt");
    file.assert_committed_lines(lines!["generated by AI before hooks".ai()]);
    assert!(
        commit
            .authorship_log
            .metadata
            .sessions
            .contains_key(&recovered_session_id),
        "recovered note should include the session-event session record"
    );
}

#[test]
fn test_session_event_recovery_does_not_override_known_human_checkpoint() {
    let (_metrics_db_dir, metrics_db_path) = isolated_metrics_db_path();
    let repo =
        TestRepo::new_with_daemon_env(&[("GIT_AI_TEST_METRICS_DB_PATH", metrics_db_path.as_str())]);
    repo.git(&["commit", "--allow-empty", "-m", "initial"])
        .expect("initial empty commit should succeed");

    let file_path = repo.path().join("human.txt");
    fs::write(&file_path, "typed by a human\n").unwrap();
    repo.git_ai(&["checkpoint", "mock_known_human", "human.txt"])
        .expect("known-human checkpoint should succeed");
    let recovered_session_id = insert_session_event(
        &metrics_db_path,
        file_mtime_secs(&file_path),
        "external-human-nearby-session",
        "tool-use-human-nearby",
        None,
    );

    let commit = repo
        .stage_all_and_commit("Known human stays human")
        .expect("commit should succeed");

    let mut file = repo.filename("human.txt");
    file.assert_committed_lines(lines!["typed by a human".human()]);
    assert!(
        !commit
            .authorship_log
            .metadata
            .sessions
            .contains_key(&recovered_session_id),
        "nearby session event must not be used when explicit human attribution exists"
    );
}

#[test]
fn test_session_event_recovery_ignores_events_outside_window() {
    let (_metrics_db_dir, metrics_db_path) = isolated_metrics_db_path();
    let repo =
        TestRepo::new_with_daemon_env(&[("GIT_AI_TEST_METRICS_DB_PATH", metrics_db_path.as_str())]);
    repo.git(&["commit", "--allow-empty", "-m", "initial"])
        .expect("initial empty commit should succeed");

    let file_path = repo.path().join("outside.txt");
    fs::write(&file_path, "outside the window\n").unwrap();
    let file_ts = file_mtime_secs(&file_path);
    let recovered_session_id = insert_session_event(
        &metrics_db_path,
        file_ts.saturating_sub(10),
        "external-outside-window-session",
        "tool-use-outside-window",
        None,
    );

    let commit = repo
        .stage_all_and_commit("Outside window stays unknown")
        .expect("commit should succeed");

    let mut file = repo.filename("outside.txt");
    file.assert_committed_lines(lines!["outside the window".unattributed_human()]);
    assert!(
        !commit
            .authorship_log
            .metadata
            .sessions
            .contains_key(&recovered_session_id),
        "outside-window session event must not recover attribution"
    );
}

#[test]
fn test_session_event_recovery_rejects_ambiguous_time_only_sessions() {
    let (_metrics_db_dir, metrics_db_path) = isolated_metrics_db_path();
    let repo =
        TestRepo::new_with_daemon_env(&[("GIT_AI_TEST_METRICS_DB_PATH", metrics_db_path.as_str())]);
    repo.git(&["commit", "--allow-empty", "-m", "initial"])
        .expect("initial empty commit should succeed");

    let file_path = repo.path().join("ambiguous.txt");
    fs::write(&file_path, "ambiguous time only\n").unwrap();
    let file_ts = file_mtime_secs(&file_path);
    let first_session = insert_session_event(
        &metrics_db_path,
        file_ts,
        "external-ambiguous-first",
        "tool-use-ambiguous-first",
        None,
    );
    let second_session = insert_session_event(
        &metrics_db_path,
        file_ts,
        "external-ambiguous-second",
        "tool-use-ambiguous-second",
        None,
    );

    let commit = repo
        .stage_all_and_commit("Ambiguous sessions stay unknown")
        .expect("commit should succeed");

    let mut file = repo.filename("ambiguous.txt");
    file.assert_committed_lines(lines!["ambiguous time only".unattributed_human()]);
    assert!(
        !commit
            .authorship_log
            .metadata
            .sessions
            .contains_key(&first_session)
            && !commit
                .authorship_log
                .metadata
                .sessions
                .contains_key(&second_session),
        "ambiguous time-only session events must not recover attribution"
    );
}
